# Generated by Django 5.1.1 on 2025-07-17 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sgtd", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkins",
            name="update_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
