# Generated by Django 4.2 on 2025-03-02 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sgtd", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teams",
            name="speaker_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams_speaker_1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teams",
            name="speaker_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams_speaker_2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teamresults",
            name="draw",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="team_results",
                to="sgtd.draws",
            ),
        ),
        migrations.AddField(
            model_name="teamresults",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="team_results",
                to="sgtd.teams",
            ),
        ),
        migrations.AddField(
            model_name="speakerresults",
            name="draw",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="speaker_results",
                to="sgtd.draws",
            ),
        ),
        migrations.AddField(
            model_name="speakerresults",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="speaker_results",
                to="sgtd.speakers",
            ),
        ),
        migrations.AddField(
            model_name="drawsadjudicators",
            name="adjudicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="draws_adjudicators_adjudicator",
                to="sgtd.adjudicators",
            ),
        ),
        migrations.AddField(
            model_name="drawsadjudicators",
            name="draw",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="draws_adjudicators_draw",
                to="sgtd.adjudicators",
            ),
        ),
        migrations.AddField(
            model_name="draws",
            name="adjudicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="draws",
                to="sgtd.adjudicators",
            ),
        ),
        migrations.AddField(
            model_name="draws",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="draws",
                to="sgtd.rounds",
            ),
        ),
        migrations.AddField(
            model_name="draws",
            name="speaker_position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="draws",
                to="sgtd.speakers",
            ),
        ),
        migrations.AddField(
            model_name="adjudicators",
            name="team_representation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adjudicators",
                to="sgtd.teams",
            ),
        ),
    ]
