# Generated by Django 5.1.1 on 2025-07-17 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sgtd", "0002_alter_checkins_update_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkins",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkins",
                to="sgtd.rounds",
            ),
        ),
        migrations.AlterField(
            model_name="checkins",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkins",
                to="sgtd.speakers",
            ),
        ),
    ]
