# Generated by Django 4.2 on 2025-03-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tournaments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="tournament name")),
                ("description_tournament", models.TextField(null=True)),
                ("tournament_status", models.TextField()),
                ("avoid_same_institution", models.BooleanField()),
                ("shortname", models.TextField(null=True)),
                ("place", models.TextField(null=True)),
                ("missing_feedbacks", models.BooleanField()),
                ("feedback_description", models.TextField(null=True)),
                ("speaker_criteria", models.JSONField(null=True)),
                ("minimum_panel_score", models.IntegerField()),
                ("check_in", models.BooleanField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("team_criteria", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField()),
            ],
        ),
    ]
