# Generated by Django 5.2.4 on 2025-07-23 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='tournament name')),
                ('description_tournament', models.TextField(null=True)),
                ('tournament_status', models.TextField()),
                ('avoid_same_institution', models.BooleanField()),
                ('shortname', models.TextField(null=True)),
                ('place', models.TextField(null=True)),
                ('missing_feedbacks', models.BooleanField()),
                ('feedback_description', models.TextField(null=True)),
                ('minimum_panel_score', models.IntegerField()),
                ('check_in', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usertournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(editable=False)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertournaments', to='app.tournaments')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
