# Generated by Django 5.1.1 on 2025-07-17 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('province', models.TextField(unique=True)),
                ('is_active', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='tournament name')),
                ('description_tournament', models.TextField(null=True)),
                ('tournament_status', models.TextField()),
                ('avoid_same_institution', models.BooleanField()),
                ('shortname', models.TextField(null=True)),
                ('place', models.TextField(null=True)),
                ('missing_feedbacks', models.BooleanField()),
                ('feedback_description', models.TextField(null=True)),
                ('minimum_panel_score', models.IntegerField()),
                ('check_in', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Usertournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(editable=False)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertournaments', to='app.tournaments')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertournaments', to='app.users')),
            ],
        ),
    ]
