# Generated by Django 5.1.1 on 2025-07-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="province",
            field=models.TextField(),
        ),
    ]
