# Generated by Django 5.1.1 on 2025-07-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_users_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_authenticated',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
