# Generated by Django 5.1.1 on 2025-07-14 05:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournaments",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="tournaments",
            name="speaker_criteria",
        ),
        migrations.RemoveField(
            model_name="tournaments",
            name="team_criteria",
        ),
        migrations.RemoveField(
            model_name="tournaments",
            name="updated_at",
        ),
        migrations.CreateModel(
            name="Usertournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.TextField(editable=False)),
                (
                    "tournament",
                    models.ManyToManyField(
                        blank=True,
                        editable=False,
                        related_name="usertournaments",
                        to="app.tournaments",
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(
                        blank=True,
                        editable=False,
                        related_name="usertournaments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
