# Generated by Django 5.1.1 on 2025-07-14 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_tournaments_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertournament",
            name="tournament",
        ),
        migrations.RemoveField(
            model_name="usertournament",
            name="user",
        ),
        migrations.AddField(
            model_name="usertournament",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usertournaments",
                to="app.tournaments",
            ),
        ),
        migrations.AddField(
            model_name="usertournament",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usertournaments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
